# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('reply_only_for_this_keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_description', models.CharField(max_length=50)),
                ('facebook_application_id', models.CharField(max_length=50)),
                ('facebook_application_secret', models.CharField(max_length=50)),
                ('ouath_token', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookFanPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_page_description', models.CharField(max_length=50)),
                ('fan_page_id', models.CharField(max_length=30)),
                ('facebook_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbautoreply.FacebookAccount')),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('list_description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedMessageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('predefined_message_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbautoreply.PredefinedMessage')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='facebook_account_to_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbautoreply.FacebookAccount'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_list_to_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbautoreply.PredefinedMessage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='set_auto_reply_for_fan_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbautoreply.FacebookFanPage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
