# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='ouath_token',
            field=models.CharField(max_length=500),
        ),
    ]
