# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0003_auto_20160812_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='autoresponder_type',
            field=models.CharField(choices=[('1', 'Send replies to inbox messages'), ('2', 'Post replies to users comments')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AutoresponderType',
        ),
    ]
