# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0004_auto_20160812_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='reply_only_for_this_keyword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
