# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
