# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0008_remove_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_text',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(),
        ),
    ]
