# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0009_auto_20160925_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='ArchiveMessage',
        ),
    ]
