# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbautoreply', '0010_auto_20161004_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
